spring.datasource.url=jdbc:postgresql://localhost:5432/techcupdb
spring.datasource.username=postgres
spring.datasource.password=manchas
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=clave-secreta-techcup-futbol-2024-muy-larga-para-hs256
jwt.expiration=3600000

## Logs en un archivo
 
logging.file.name=logs/techcup.log
logging.level.root=INFO
logging.level.com.techcup_futbol=DEBUG