spring.datasource.url=jdbc:postgresql://localhost:5432/lab8db 
spring.datasource.username=El_cartel_de_la_empanda
spring.datasource.password=changua
spring.datasource.driver-class-name=org.postgresql.Driver 
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true 
spring.jpa.properties.hibernate.format_sql=true 
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect